# Generated by Django 3.0.5 on 2020-04-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simple', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='imga/')),
                ('name', models.CharField(max_length=20)),
                ('about', models.CharField(max_length=1000)),
            ],
        ),
    ]
